spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/beaver_db?useSSL=false&serverTimezone=UTC'
    username: bestuser
    password: bestuser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate